swagger: "2.0"
info:
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  title: "ArgentBank : API documentation for user's transaction"
  termsOfService: "http://swagger.io/terms/"
host: "localhost:3001"
basePath: "/api/v1"
schemes:
  - "https"
  - "http"

paths:
  /transactions:
    post:
      tags:
        - "Transactions in general"
      summary: "Create an user's transaction"
      description: "Create a transaction"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "201":
          description: "Successfully created a transaction"
        "404":
          description: "Not found"
        "500":
          description: "Internal Server Error"
      security:
        - Bearer: []
    get:
      tags:
        - "Transactions in general"
      summary: "Get all transactions in details"
      description: "Get all transactions in details"
      parameters:
        - in: "body"
          name: "body"
          required: true
          schema:
            $ref: "#/definitions/Transaction"
      responses:
        "200":
          description: "Successfully get transation"
        "404":
          description: "Not found"
        "500":
          description: "Internal Server Error"
      security:
        - Bearer: []
  /transactions/{userId}:
    get:
      tags:
        - "Transaction for a specific user"
      summary: "Find transaction details by using a specific user's id"
      description: "Get an user's transaction"
      parameters:
        - name: "userId"
          in: "path"
          description: "return id of transaction"
          required: true
          type: "integer"
      responses:
        "200":
          description: "Successfully get transation"
        "404":
          description: "Not found"
        "500":
          description: "Internal Server Error"
      security:
        - Bearer: []
    put:
      tags:
        - "Transaction for a specific user"
      summary: "Update transaction details by using a specific user's id"
      description: "Update an user's transaction"
      parameters:
        - name: "userId"
          in: "path"
          description: "ID of transaction to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "Successfully update transation"
        "404":
          description: "Not found"
        "500":
          description: "Internal Server Error"
      security:
        - Bearer: []
    delete:
      tags:
        - "Transaction for a specific user"
      summary: "Delete transaction"
      description: "Delete transaction by using a specific user's id"
      parameters:
        - name: "userId"
          in: "path"
          description: "user's transaction id"
          required: true
          type: "integer"
      responses:
        "200":
          description: "Successfully delete transaction"
        "404":
          description: "Not found"
        "500":
          description: "Internal Server Error"
      security:
        - Bearer: []

definitions:
  Transaction:
    type: "object"
    properties:
      id:
        type: "integer"
        description: "id"
      date:
        type: "string"
        description: "date"
      descritpion:
        type: "string"
        description: "description"
      amount:
        type: "number"
        description: " amount"
      balance:
        type: "number"
        description: "balance after transaction"
      title:
        type: "string"
        description: "title"

securityDefinitions:
  Bearer:
    type: "apiKey"
    name: "Authorization"
    in: "header"
